### ISSUE TITLE
Responder's handler never fires

### ISSUE THREAD

**Issue by mitchellporter** [jaredsinclair/JTSReachability#8]
I just played with this for about 20 minutes and can't get it to work.

I've tried the init method as well as the singleton, setup the responder, add the handler block.

Network status is always `NotReachable`. I'll run the app on my iPhone 6, leave switch off Wifi, come back to the app and the handler never fires and the network status is always `NotReachable`.

Have tried setting this up both in the app delegate on `didFinishLaunchingWithOptions:` and in some of my view controllers.

I just did a quick test with this repo's example project and it works properly: https://github.com/pkh/PKHReachability

Not sure why this isn't working.

**Comment by jaredsinclair** [comment]
Please post some sample code or a sample project.

**Comment by mitchellporter** [comment]
Hey Jared,

There's not really any sample code to post. I simply copy/pasted the init and singleton code included in the read me info for the repo, both in the app delegate and my view controller's `viewWillAppear:` and `viewDidAppear:` methods.

**Comment by jaredsinclair** [comment]
Can you try eliminating the view controller from the equation and putting that handler in `application:didFinishLaunchingWithOptions:`?

**Comment by mitchellporter** [comment]
The original testing was done with 100% of the code in `application:didFinishLaunchingWithOptions:`, I only added the View Controller into the mix after it wasn't working in the app's delegate.

**Comment by jaredsinclair** [comment]
I really can't troubleshoot this without your code. When I test here everything works as expected.

**Comment by jaredsinclair** [comment]
Sample project [here](https://www.dropbox.com/s/ry50rvma9twhh7f/TestoChango.zip?dl=0). Works in simulator and on iPhone 6 Plus, both tested using iOS 8.

**Comment by mitchellporter** [comment]
So just to clarify, if you run that sample project on the simulator, that block will fire in the app delegate and one of those NSLogs will output to the console?

**Comment by jaredsinclair** [comment]
Yep. Or on a device.

**Comment by jaredsinclair** [comment]
But not as soon as you run the app.

**Comment by jaredsinclair** [comment]
The blocks only run when the network status changes.

**Comment by jaredsinclair** [comment]
Launch the app -> toggle airplane mode on -> Log.
Launch the app -> toggle airplane mode off -> Log.
Launch the app -> toggle wifi on/off -> Log.

**Comment by mitchellporter** [comment]
This is very strange. If I run your sample project on the simulator and set a breakpoint in the handler block, I can toggle wifi on and off and the block fires successfully every single time.

If I copy the same code over into my project, the block never fires.

**Comment by mitchellporter** [comment]
At this point i have no idea why this isn't working in my project when I'm literally copying over the same code from the demo project. Maybe it's something in my project settings? I'm using cocoapods as well.

**Comment by griffithJ** [comment]
FYI I am seeing the same as mitchellporter. Test project works fine on my iPhone 6, iOS 8.3 (12F70); production code does not. Same code has been working for months. I set a breakpoint inside JTSReachability ReachabilityCallback and it does not get hit in the production code. No cocoapods here; will continue to investigate.

**Comment by griffithJ** [comment]
It looks like if you initially call [JTSReachabilityResponder sharedInstance] from a background thread, it schedules all callbacks on that thread's run loop. Calling it from the main thread early in the application launch (in applicationDidFinishLaunchingWithOptions, before kicking off any background processing) to ensure the singleton is first instantiated on the main thread seems to get it working properly.

The documentation does say all blocks must be added or removed on the main thread, but perhaps it could be clarified that the shared instance must be created on the main thread as well.

**Comment by mitchellporter** [comment]
@griffithJ I've been testing the code inside of applicationDidFinishLaunchingWithOptions this entire time, before any background processing is taking place. Glad you got it working in your project, but still doesn't explain what I'm experiencing.
